import type { Project } from '@/types/project';

export const mockProjects: Project[] = [
  {
    id: "1",
    title: "Modern Office Complex",
    slug: "modern-office-complex",
    description:
      "A contemporary office building featuring sustainable design principles and innovative workspace solutions.",
    status: "completed",
    is_public: true,
    view_count: 1247,
    interaction_count: 89,
    thumbnail_url: "/placeholder.svg?height=300&width=400",
    created_at: "2023-01-15T10:30:00Z",
    completion_date: "2023-06-30",
    gltf_url: "/models/office-complex.gltf",
    user: {
      username: "jane_architect",
      first_name: "Jane",
      last_name: "Smith",
    },
    building_typology: {
      name: "Commercial",
      description: "Office and commercial buildings",
    },
    location: {
      name: "San Francisco, CA",
      latitude: 37.7749,
      longitude: -122.4194,
    },
    tags: [{ name: "Office" }, { name: "Modern" }, { name: "Glass" }, { name: "Sustainable" }, { name: "LEED" }],
    software: [
      { name: "Revit", vendor: "Autodesk" },
      { name: "3ds Max", vendor: "Autodesk" },
      { name: "V-Ray", vendor: "Chaos Group" },
    ],
  },
  {
    id: "2",
    title: "Residential Tower",
    slug: "residential-tower",
    description: "A 40-story residential tower designed with sustainability and community in mind.",
    status: "completed",
    is_public: true,
    view_count: 892,
    interaction_count: 67,
    thumbnail_url: "/placeholder.svg?height=300&width=400",
    created_at: "2022-08-20T14:15:00Z",
    completion_date: "2022-12-15",
    gltf_url: "/models/residential-tower.gltf",
    user: {
      username: "david_designer",
      first_name: "David",
      last_name: "Park",
    },
    building_typology: {
      name: "Residential",
      description: "Housing and residential buildings",
    },
    location: {
      name: "New York, NY",
      latitude: 40.7128,
      longitude: -74.006,
    },
    tags: [{ name: "Residential" }, { name: "High-rise" }, { name: "Sustainable" }, { name: "Community" }],
    software: [
      { name: "ArchiCAD", vendor: "Graphisoft" },
      { name: "Lumion", vendor: "Act-3D" },
      { name: "AutoCAD", vendor: "Autodesk" },
    ],
  },
  {
    id: "3",
    title: "Cultural Center",
    slug: "cultural-center",
    description: "A modern cultural center featuring flexible exhibition spaces and community areas.",
    status: "completed",
    is_public: true,
    view_count: 1456,
    interaction_count: 123,
    thumbnail_url: "/placeholder.svg?height=300&width=400",
    created_at: "2023-03-10T09:45:00Z",
    completion_date: "2023-09-20",
    gltf_url: "/models/cultural-center.gltf",
    user: {
      username: "sarah_studios",
      first_name: "Sarah",
      last_name: "Johnson",
    },
    building_typology: {
      name: "Cultural",
      description: "Museums, galleries, and cultural facilities",
    },
    location: {
      name: "Chicago, IL",
      latitude: 41.8781,
      longitude: -87.6298,
    },
    tags: [{ name: "Cultural" }, { name: "Public" }, { name: "Contemporary" }, { name: "Exhibition" }],
    software: [
      { name: "Rhino", vendor: "Robert McNeel & Associates" },
      { name: "Grasshopper", vendor: "Robert McNeel & Associates" },
      { name: "Enscape", vendor: "Enscape" },
    ],
  },
  {
    id: "4",
    title: "Educational Campus",
    slug: "educational-campus",
    description: "A comprehensive educational facility with multiple buildings and outdoor learning spaces.",
    status: "ongoing",
    is_public: true,
    view_count: 634,
    interaction_count: 45,
    thumbnail_url: "/placeholder.svg?height=300&width=400",
    created_at: "2021-11-05T16:20:00Z",
    completion_date: "2024-05-30",
    gltf_url: "/models/educational-campus.gltf",
    user: {
      username: "mike_arch",
      first_name: "Michael",
      last_name: "Chen",
    },
    building_typology: {
      name: "Educational",
      description: "Schools, universities, and educational facilities",
    },
    location: {
      name: "Boston, MA",
      latitude: 42.3601,
      longitude: -71.0589,
    },
    tags: [{ name: "Education" }, { name: "Campus" }, { name: "Brick" }, { name: "Traditional" }],
    software: [
      { name: "SketchUp", vendor: "Trimble" },
      { name: "LayOut", vendor: "Trimble" },
      { name: "Photoshop", vendor: "Adobe" },
    ],
  },
  {
    id: "5",
    title: "Healthcare Facility",
    slug: "healthcare-facility",
    description: "A state-of-the-art healthcare facility designed for patient comfort and operational efficiency.",
    status: "completed",
    is_public: true,
    view_count: 789,
    interaction_count: 56,
    thumbnail_url: "/placeholder.svg?height=300&width=400",
    created_at: "2023-02-28T11:10:00Z",
    completion_date: "2023-08-15",
    gltf_url: "/models/healthcare-facility.gltf",
    user: {
      username: "lisa_health",
      first_name: "Lisa",
      last_name: "Wong",
    },
    building_typology: {
      name: "Healthcare",
      description: "Hospitals, clinics, and medical facilities",
    },
    location: {
      name: "Seattle, WA",
      latitude: 47.6062,
      longitude: -122.3321,
    },
    tags: [{ name: "Healthcare" }, { name: "Modern" }, { name: "Accessible" }, { name: "Healing" }],
    software: [
      { name: "Revit", vendor: "Autodesk" },
      { name: "Navisworks", vendor: "Autodesk" },
      { name: "3ds Max", vendor: "Autodesk" },
    ],
  },
  {
    id: "6",
    title: "Mixed-Use Development",
    slug: "mixed-use-development",
    description: "An innovative mixed-use development combining retail, office, and residential spaces.",
    status: "completed",
    is_public: true,
    view_count: 1123,
    interaction_count: 78,
    thumbnail_url: "/placeholder.svg?height=300&width=400",
    created_at: "2022-05-12T13:30:00Z",
    completion_date: "2022-11-20",
    gltf_url: "/models/mixed-use.gltf",
    user: {
      username: "robert_urban",
      first_name: "Robert",
      last_name: "Taylor",
    },
    building_typology: {
      name: "Mixed-Use",
      description: "Buildings with multiple functions",
    },
    location: {
      name: "Austin, TX",
      latitude: 32.7767,
      longitude: -96.797,
    },
    tags: [{ name: "Mixed-Use" }, { name: "Urban" }, { name: "Retail" }, { name: "Transit-Oriented" }],
    software: [
      { name: "ArchiCAD", vendor: "Graphisoft" },
      { name: "Cinema 4D", vendor: "Maxon" },
      { name: "After Effects", vendor: "Adobe" },
    ],
  },
]